"""
render.py — writes docs/index.html, a static dashboard served free by
GitHub Pages. No server, no JS framework, no external requests: the whole
page is regenerated by the same Actions run that checks the levels.

Phone-first layout. Add to homescreen and it behaves like an app.
"""

from __future__ import annotations

import html
import os
from typing import Dict, List

from lib.clock import fmt_local, now_local

OUT_PATH = os.environ.get("DASHBOARD_PATH", "docs/index.html")

STATE_STYLE = {
    "BUY_WATCH": ("#1a7f37", "#dafbe1", "BUY WATCH"),
    "BROKEN": ("#cf222e", "#ffebe9", "BROKEN"),
    "HOLD_FIRE": ("#9a6700", "#fff8c5", "HOLD FIRE"),
    "WAIT": ("#57606a", "#f6f8fa", "WAIT"),
    "STALE": ("#8250df", "#fbefff", "NO DATA"),
}

CSS = """
:root { color-scheme: light dark; --bg:#fff; --fg:#1f2328; --muted:#57606a; --line:#d1d9e0; --card:#fff; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#0d1117; --fg:#e6edf3; --muted:#9198a1; --line:#3d444d; --card:#151b23; }
}
* { box-sizing:border-box; }
body { margin:0; padding:16px; background:var(--bg); color:var(--fg);
  font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
h1 { font-size:19px; margin:0 0 2px; }
.sub { color:var(--muted); font-size:13px; margin-bottom:16px; }
.card { border:1px solid var(--line); border-radius:12px; padding:14px;
  margin-bottom:10px; background:var(--card); }
.row { display:flex; justify-content:space-between; align-items:baseline; gap:8px; }
.sym { font-size:19px; font-weight:700; letter-spacing:-.2px; }
.price { font-size:19px; font-variant-numeric:tabular-nums; }
.badge { display:inline-block; padding:2px 9px; border-radius:999px;
  font-size:11px; font-weight:700; letter-spacing:.4px; }
.up { color:#1a7f37; } .down { color:#cf222e; }
.levels { display:grid; grid-template-columns:repeat(4,1fr); gap:6px;
  margin-top:12px; font-size:12px; text-align:center; }
.levels div span { display:block; color:var(--muted); font-size:10px;
  text-transform:uppercase; letter-spacing:.5px; }
.levels b { font-variant-numeric:tabular-nums; font-weight:600; }
.reasons { margin:10px 0 0; padding:0; list-style:none;
  font-size:12px; color:var(--muted); }
.reasons li:before { content:"• "; }
.ticket { margin-top:12px; padding:10px; border-radius:8px;
  background:#dafbe1; color:#0a3622; font-size:13px; }
@media (prefers-color-scheme: dark) { .ticket { background:#0f2f1a; color:#b4f0c6; } }
.ticket b { display:block; margin-bottom:4px; }
.foot { color:var(--muted); font-size:11px; margin-top:20px;
  padding-top:12px; border-top:1px solid var(--line); }
"""


def _card(result: Dict) -> str:
    symbol = result["symbol"]
    snap = result["snap"]
    cfg = result["cfg"]
    fg, bg, label = STATE_STYLE.get(result["state"], STATE_STYLE["WAIT"])

    if snap:
        cls = "up" if snap["day_pct"] >= 0 else "down"
        price = '<span class="price {}">${:.2f} {:+.2f}%</span>'.format(
            cls, snap["price"], snap["day_pct"])
    else:
        price = '<span class="price">—</span>'

    levels = ""
    if snap:
        levels = (
            '<div class="levels">'
            '<div><span>stop</span><b>{}</b></div>'
            '<div><span>reclaim</span><b>{}</b></div>'
            '<div><span>t1</span><b>{}</b></div>'
            '<div><span>50 / 200 dma</span><b>{} / {}</b></div>'
            "</div>"
        ).format(cfg.get("invalidation", "—"), cfg.get("reclaim", "—"),
                 cfg.get("t1", "—"), snap.get("sma50") or "—", snap.get("sma200") or "—")

    ticket_html = ""
    t = result.get("ticket")
    if t and t.get("valid") and t.get("kind") == "BUY":
        ticket_html = (
            '<div class="ticket"><b>📋 Prepared ticket — approve or deny</b>'
            "BUY {shares} {sym} · limit ${lo}–${hi} · target ${tgt}<br>"
            "stop ${stop} ({kind}) · thesis breaks below ${thesis}<br>"
            "risk ${risk} → reward ${rew} (R:R {rr})<br>expires {exp}</div>"
        ).format(shares=t["shares"], sym=symbol, lo=t["limit_band"][0], hi=t["limit_band"][1],
                 stop=t["stop"], kind=html.escape(t.get("stop_kind", "stop")),
                 thesis=t.get("thesis_stop", "—"), tgt=t["target"],
                 risk=t["risk_usd"], rew=t["reward_usd"],
                 rr=t["reward_risk"], exp=html.escape(t["expires_label"]))

    reasons = "".join("<li>{}</li>".format(html.escape(r)) for r in result["reasons"])

    return (
        '<div class="card">'
        '<div class="row"><span class="sym">{sym}</span>{price}</div>'
        '<div class="row" style="margin-top:6px">'
        '<span class="badge" style="color:{fg};background:{bg}">{label}</span></div>'
        "{levels}"
        '<ul class="reasons">{reasons}</ul>'
        "{ticket}"
        "</div>"
    ).format(sym=symbol, price=price, fg=fg, bg=bg, label=label,
             levels=levels, reasons=reasons, ticket=ticket_html)


def write(results: List[Dict]) -> str:
    order = {"BUY_WATCH": 0, "BROKEN": 1, "HOLD_FIRE": 2, "WAIT": 3, "STALE": 4}
    ranked = sorted(results, key=lambda r: (order.get(r["state"], 9), r["symbol"]))

    page = (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<meta http-equiv="refresh" content="300">'
        '<meta name="apple-mobile-web-app-capable" content="yes">'
        "<title>Signal Desk</title><style>{css}</style></head><body>"
        "<h1>Signal Desk</h1>"
        '<div class="sub">updated {stamp} · refreshes every 5 min</div>'
        "{cards}"
        '<div class="foot">Levels are rules you set, not predictions. '
        "Nothing here executes. Data via yfinance on a ~5–15 min delay — "
        "verify in your broker before acting.</div>"
        "</body></html>"
    ).format(css=CSS, stamp=fmt_local(now_local()),
             cards="".join(_card(r) for r in ranked))

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as fh:
        fh.write(page)
    return OUT_PATH
